apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type:  {{ .Values.secrets.type }}
data:
    postgres-username: {{ index .Values.secrets "postgres-username" | b64enc | quote }}
    postgres-password: {{ index .Values.secrets "postgres-password" | b64enc | quote }}